<a href="https://colab.research.google.com/github/leejungp2/dl-study/blob/main/260129_00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### Creating tensors (20)

Pytorch tensors are created using torch.Tensor()= https://docs.pytorch.org/docs/stable/index.html
-> 적어도 10분 읽어보시오

- 1,2,3차원 파이썬 데이터들을 딥러닝 입력으로 넣고싶을 대 tensor 형태로 바꿔줘야 GPU 에 올릴 수 있음

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

- 이렇게 되면 0차원 텐서 tensor(7)이 만들어진거임   
  1차원은 리스트 []로 감싸야되는데 안 감싸졌으므로 0차원   
  아래 코드로 확인해볼 수 있음

In [ ]:
scalar.ndim

0

- 이러한 텐서를 원래대로 되돌리려면 아래와 같이 하면 됨

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors (21)

Why random tensors?

Random tensors are important because the way many nueral networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data`

- 왜 랜덤텐서를 사용하는가   
  - 랜덤텐서가 학습 초기값인데 이거를 조금씩 다르게 줘야 학습이 다양하게 됨.   
    예를 들어서 0으로 똑같으면 다 같은 결과값을 냄

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2812, 0.0980, 0.3332, 0.6910],
        [0.2611, 0.6615, 0.0894, 0.3876],
        [0.2635, 0.1676, 0.2619, 0.2249]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

### 0,1 Tensors (22)

### Range Tensors (23)

### Tensor Datatypes (24)
- top3 에러   
  - 잘못된 데이터타입 (확인 tensor.dtype)   
  - 잘못된 shape (확인 tensor.shape)
  - 잘못된 디바이스 (확인 tensor.device)

### Tensor 정보 확인 (25)

### Tensor 덧셈뺄셈 (26)