<a href="https://colab.research.google.com/github/leejungp2/dl-study/blob/main/260208_00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.
(7,7) 크기의 랜덤 텐서 만들기

In [1]:
# Import torch
import torch

# Create random tensor
## 랜덤 텐서 .rand
X = torch.rand(size = (7, 7))
X, X.shape # 차원, 크기

(tensor([[0.9806, 0.7320, 0.4113, 0.5469, 0.4155, 0.7501, 0.0268],
         [0.0796, 0.4156, 0.5254, 0.9631, 0.0663, 0.0389, 0.2495],
         [0.1850, 0.1927, 0.8863, 0.7143, 0.9044, 0.6546, 0.1958],
         [0.9397, 0.0646, 0.8373, 0.4782, 0.0724, 0.8025, 0.7734],
         [0.5819, 0.6785, 0.3978, 0.9930, 0.6927, 0.2579, 0.4477],
         [0.7823, 0.4766, 0.9423, 0.7436, 0.1045, 0.1027, 0.8961],
         [0.2189, 0.1773, 0.2897, 0.4136, 0.8694, 0.7282, 0.7403]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

위 문제의 랜덤 텐서 * 또 다른 (1,7)크기의 랜덤 텐서 곱하기.
transpose 필요할 수 있음.

In [6]:
# Create another random tensor
X2 = torch.rand(size = (1, 7))
X2, X2.shape

# Perform matrix multiplication
X @ X2.T
Y = torch.matmul(X, X2.T)
Y, Y.shape

## 이전 강의에서는 3가지 방법 나왔음: 1) 직접 구현 2) @ 3) torch.matmul

(tensor([[2.3261],
         [1.6304],
         [2.6291],
         [2.6887],
         [2.5248],
         [2.7004],
         [1.9963]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

- seed: 난수 생성 시작 번호를 0으로 두기

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7,7))
X2 = torch.rand(size=(1,7))

# Matrix multiply tensors
Y = torch.matmul(X, X2.T)
Y, Y.shape
## 동일한 시드(예: 0)를 주면 알고리즘이 항상 같은 계산 경로를 따르므로, 다음에 나올 숫자들의 순서와 값이 100% 동일하게 유지됨


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

CPU 랜덤 시드 설정한 텐서 2개 생성 후 GPU로 보내기

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.
가장 큰 값이 어디(인덱스)에 있는지

In [16]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

크기 10인 4차원 텐서 생성 (나머지는 다 크기 1). 차원 제거하여 최종적으로 (10)크기의 1차원 텐서로 바꾸기.

In [17]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
